# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/carson/poly/cpe439/hdmi_2_vga/project_1.cache/wt [current_project]
set_property parent.project_path /home/carson/poly/cpe439/hdmi_2_vga/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/carson/poly/cpe439/vivado-library-master [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/dvi2rgb_0_synth_1/dvi2rgb_0.dcp
set_property used_in_implementation false [get_files /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/dvi2rgb_0_synth_1/dvi2rgb_0.dcp]
add_files -quiet /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/rgb2vga_0_synth_1/rgb2vga_0.dcp
set_property used_in_implementation false [get_files /home/carson/poly/cpe439/hdmi_2_vga/project_1.runs/rgb2vga_0_synth_1/rgb2vga_0.dcp]
read_verilog -library xil_defaultlib {
  /home/carson/poly/cpe439/hdmi_2_vga/img_proc.v
  /home/carson/poly/cpe439/hdmi_2_vga/top.v
}
read_xdc /home/carson/poly/cpe439/hdmi_2_vga/constraints.xdc
set_property used_in_implementation false [get_files /home/carson/poly/cpe439/hdmi_2_vga/constraints.xdc]

synth_design -top top -part xc7z010clg400-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
