# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/dvi2rgb_0.xci
# IP: The module: 'dvi2rgb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/dvi2rgb_0.xci
# IP: The module: 'dvi2rgb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/hgfs/Google Drive/poly/CPE439/Resistor-Value-Detector/project_1.srcs/sources_1/ip/dvi2rgb_0_2/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
